// Proper HTTP status code mapping for responses

const RESPONSE_CODES = {
    SUCCESS: 200,
    OPERATION_FAILED: 500,
    NO_DATA_FOUND: 404,
    INACTIVE_ACCOUNT: 403,
    OTP_NOT_VERIFIED: 401,
    INVALID_API_KEY: 401,
    INVALID_TOKEN: 401,
    INVALID_ROLE: 403,
    REQUEST_ERROR: 400,
    NOT_APPROVED: 403,
    SOCIAL_ID_NOT_REGISTER: 404,
    NOT_REGISTER: 404
};

module.exports = RESPONSE_CODES;